### ISSUE TITLE
Moving Components when importing a JSON

### ISSUE THREAD

**Issue by peytontierney** [CIDARLAB/3DuF#133]
After importing a previously designed file, moving these components no longer works.
<img width="1201" alt="screen shot 2018-07-11 at 3 39 21 pm" src="https://user-images.githubusercontent.com/39597010/42595606-d235219c-8520-11e8-8ffe-f3baad44f086.png">

**Comment by rkrishnasanka** [comment]
Turns out when you're saving the design, it's not serializing the `Component` information into the JSON. This, in turn, makes it 3DuF 'forget' the component properties of the feature you place. Hence it's not allowing you to do all the changes that you should be able to. I will fix this soon but unfortunately, you would have to redesign the chip in that case. You'll get notified when I fix this serialization error.
