### ISSUE TITLE
Cannot export SVGs with only channels

### ISSUE THREAD

**Issue by Nesciosquid** [CIDARLAB/3DuF#17]

**Comment by rkrishnasanka** [comment]
Turns out because the port feature has some gradient on it, the system forces the generation of an `<svg></svg>` element. Otherwise, the issue is that it just generates path `<g></g>` elements for the device. The stack overflow thread has some answers but I need to implement it and see what happens.

https://jsfiddle.net/ibowankenobi/juem7f80/1/

**Comment by rkrishnasanka** [comment]
Implemented as of commit - 2545e9e5107388d6f9d0fec27bfa0b405c68d20f
