### ISSUE TITLE
Incorrect rotation of Valve3D after loading from JSON

### ISSUE THREAD

**Issue by zyrrron** [CIDARLAB/3DuF#184]
[auto rotation.zip](https://github.com/CIDARLAB/3DuF/files/4909987/auto.rotation.zip)

**Comment by rkrishnasanka** [comment]
It seems like the `orientation` parameter was not getting deleted in the JSON and messed with the load. This was an oversight missed.

Fixed in commit: 6cba8f1

Script to sanitize valves components: https://gist.github.com/rkrishnasanka/8bf7970180e0f5be37691ed95df57710

Run this script with python3 to clean up the orientation parameters
