### ISSUE TITLE
Website Freezing/Crashing when Switching Between Control and Flow Layers

### ISSUE THREAD

**Issue by JoshuaSingh33** [CIDARLAB/3DuF#238]
**Describe the bug**
When I try to switch between the control and flow layer (by clicking their respective buttons), my 3duf crashes.

**To Reproduce**
1. Go to 'select layer'
2. Click on 'control' or 'flow' (depends on what current layer is, want to switch to other, non-current layer).
3. See error

Or add a GIF

**Expected behavior**
Supposed to cleanly switch between layers and not freeze.
**Screenshots**
<img width="999" alt="3duf freezing" src="https://user-images.githubusercontent.com/44583937/115163962-2ad52c80-a07a-11eb-8196-540c7f5fe2aa.PNG">
<img width="419" alt="3duf_console" src="https://user-images.githubusercontent.com/44583937/115435650-0c854300-a1d8-11eb-8f28-5e8ddab9a607.PNG">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 10

**Additional context**

**Comment by JoshuaSingh33** [comment]
I wasn't able to attach my .json file as it said that file type is not supported (I will have to email it to you as it is too big for piazza attachment).

**Comment by msuazox** [comment]
I'm also having problems with the website being unresponsive. When I try to use the connection tools, nothing shows. At first I thought I was using it wrong, but in another tab I tried 3duf and used the connection tab first and it works. Then after a while it stops working again. 

Desktop 
- OS 
- Chrome 
- Big Sur 11.2.3

Similarly when I use the command v function, the website undos connections instead of pasting. 


https://user-images.githubusercontent.com/61927568/115661815-098b6f00-a30c-11eb-9fd7-bda34eeb987c.mov

**Comment by msuazox** [comment]
<img width="1460" alt="Screen Shot 2021-04-22 at 1 30 21 AM" src="https://user-images.githubusercontent.com/61927568/115805833-be2c9b80-a3b3-11eb-84ba-60149c4623dd.png">

**Comment by rkrishnasanka** [comment]
Any luck uploading the Zip file (containing the json) for this ?

**Comment by rkrishnasanka** [comment]
This is being fixed in v2
